import { transliterateSlug } from "./transliterate";

export interface AIProcessedNewsResult {
  title: string;
  attractiveHeadlines: string[];
  content: string; // Formatted HTML or paragraphs in Nepali
  highlights: string[]; // 3-5 bullet points
  excerpt: string;
  metaTitle: string;
  metaDescription: string;
  suggestedSlug: string;
  suggestedCategory: string;
  isBreaking: boolean;
  breakingScore: number; // 0 - 100
  breakingReason: string;
  imageSuggestions: {
    searchKeywords: string[];
    description: string;
  };
}

export interface NewsProcessOptions {
  rawText: string;
  sourceTitle?: string;
  sourceUrl?: string;
  tone?: "standard" | "analytical" | "breaking" | "simple";
  targetLength?: "short" | "medium" | "detailed";
  apiKey?: string;
}

/**
 * Clean and normalize raw pasted or scraped content
 */
export function cleanRawText(raw: string): string {
  return raw
    .replace(/<script[^>]*>.*?<\/script>/gi, "")
    .replace(/<style[^>]*>.*?<\/style>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Helper to build standard Express AI News Summary HTML box
 */
export function buildNewsSummaryBoxHtml(highlights: string[]): string {
  if (!highlights || highlights.length === 0) return "";
  const listItems = highlights
    .map((item) => `    <li>${item.replace(/^[•\-\*\s]+/, "")}</li>`)
    .join("\n");

  return `<div class="express-news-summary not-prose">
  <div class="summary-header">
    <div class="summary-title-wrap">
      <h4 class="summary-title">News Summary</h4>
    </div>
    <span class="summary-badge">Editorially reviewed.</span>
  </div>
  <ul>
${listItems}
  </ul>
</div>`;
}

/**
 * Main AI News Rewriter & Processor using Google Gemini
 */
export async function processNewsWithAI(
  options: NewsProcessOptions
): Promise<AIProcessedNewsResult> {
  const { rawText, sourceTitle, sourceUrl, tone = "standard", targetLength = "medium", apiKey } = options;

  const key =
    apiKey ||
    process.env.GEMINI_API_KEY ||
    process.env.GOOGLE_API_KEY ||
    process.env.NEXT_PUBLIC_GEMINI_API_KEY;

  if (!rawText || rawText.trim().length < 20) {
    throw new Error("कृपया कम्तीमा २० अक्षर भएको समाचार सामग्री राख्नुहोस् (Content is too short).");
  }

  // If no Gemini key is provided, provide an intelligent fallback parser
  if (!key) {
    return generateFallbackNewsResult(rawText, sourceTitle);
  }

  const prompt = `
You are a senior chief news editor and investigative journalist at 'Express Nepal' (a premier Nepali digital news portal).

YOUR TASK:
Take the provided source material—which may be from:
1. Other Nepali online portals (OnlineKhabar, Setopati, Ratopati, Kantipur, etc.)
2. YouTube news video transcripts, audio summaries, or interview notes
3. Foreign / International English news outlets

And COMPLETELY REWRITE, PARAPHRASE, EDIT, and RESTRUCTURE it into an ORIGINAL, engaging, professional Devanagari news article for 'Express Nepal'.

CRITICAL ANTI-PLAGIARISM & PARAPHRASING MANDATES:
1. DEEP REPHRASING (मौलिक पुनर्लेखन):
   - You MUST NOT copy or closely imitate sentences from the source article.
   - Deconstruct the key facts, events, quotes, and statistics, and re-narrate them in your own natural, journalistic Nepali editorial voice.
   - Change active/passive structure, combine or break paragraphs, use rich Devanagari vocabulary, and provide fresh transitions.
   - If the source is a YouTube video transcript or spoken interview, transform casual/spoken notes into polished, high-standard print journalism.
   - If the source is in English, translate accurately and adapt with cultural and political context for Nepali readers.

2. NEWS SUMMARY HIGHLIGHTS (समाचार मुख्य बुँदाहरू):
   - Generate 3 to 4 distinct, concise, and beautifully paraphrased bullet points summarizing the core essence of the news (like 'News Summary - Generated by Express AI. Editorially reviewed.').
   - Each bullet point must be complete, grammatically sound, and end with a Devanagari danda (।).

3. ARTICLE BODY IN SEMANTIC HTML:
   - Provide the complete rewritten story in clean HTML using <p> for paragraphs, <h3> for subheadings, and <blockquote> for key statements or quotes.
   - DO NOT include the title as an <h1> inside the content (title is separate).
   - Ensure the lead paragraph (पहिलो अनुच्छेद) answers: Who, What, When, Where, Why, and How.

4. 4 HIGH-IMPACT DEVANAGARI HEADLINES:
   - Headline 1 (आधिकारिक र सन्तुलित): Standard authoritative news headline.
   - Headline 2 (आकर्षक र क्लिकयोग्य): Catchy, curiosity-inducing, high-CTR headline.
   - Headline 3 (ताजा र ब्रेकिङ शैली): Urgent, breaking-news style.
   - Headline 4 (विश्लेषणात्मक वा प्रश्नमूलक): Analytical angle or investigative question.

5. SEO & CATEGORY:
   - SEO metaTitle (under 60 chars) and metaDescription (under 160 chars in Devanagari).
   - Romanized URL Slug in English (e.g. 'kathmandu-road-expansion-project-update').
   - Suggested Category name (राजनीति, अर्थतन्त्र, सूचना प्रविधि, अन्तर्राष्ट्रिय, समाज, खेलकुद, मनोरञ्जन, विचार).
   - Breaking evaluation (score 0-100, boolean flag, and 1-line Nepali explanation).
   - Image recommendations (English search keywords and visual description).

Source News Title: ${sourceTitle || "N/A"}
Source News URL: ${sourceUrl || "N/A"}
Desired Tone: ${tone} (standard, analytical, breaking, or simple)
Target Length: ${targetLength}

SOURCE CONTENT:
"""
${rawText.slice(0, 12000)}
"""

You MUST reply ONLY with a valid JSON object matching this exact structure:
{
  "title": "मुख्य छानिएको आकर्षक नेपाली शीर्षक",
  "attractiveHeadlines": [
    "शीर्षक १ (आधिकारिक)",
    "शीर्षक २ (आकर्षक/क्लिकयोग्य)",
    "शीर्षक ३ (ताजा/ब्रेकिङ शैली)",
    "शीर्षक ४ (विश्लेषणात्मक)"
  ],
  "content": "<p>पहिलो मौलिक अनुच्छेद...</p><p>दोस्रो अनुच्छेद...</p>",
  "highlights": [
    "पहिलो मुख्य बुँदा...",
    "दोस्रो मुख्य बुँदा...",
    "तेस्रो मुख्य बुँदा..."
  ],
  "excerpt": "समाचारको संक्षिप्त २ वाक्यको सारांश...",
  "metaTitle": "गुगल सर्चका लागि एसईओ शीर्षक",
  "metaDescription": "गुगल सर्चका लागि एसईओ विवरण...",
  "suggestedSlug": "romanized-url-slug-in-english",
  "suggestedCategory": "राजनीति",
  "isBreaking": false,
  "breakingScore": 45,
  "breakingReason": "यो नियमित समाचार भएकाले सामान्य श्रेणीमा पर्दछ।",
  "imageSuggestions": {
    "searchKeywords": ["keyword1", "keyword2", "keyword3"],
    "description": "Featured photo description recommendation"
  }
}
`;

  const trimmedKey = key.trim();
  let lastError: any = null;

  // 1. First, query Google's ModelService to get the exact available models for this key
  let availableModels: string[] = [];
  try {
    const listRes = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(trimmedKey)}`,
      {
        headers: {
          "x-goog-api-key": trimmedKey,
        },
      }
    );
    if (listRes.ok) {
      const listData = await listRes.json();
      if (Array.isArray(listData.models)) {
        availableModels = listData.models
          .filter((m: any) =>
            Array.isArray(m.supportedGenerationMethods) &&
            m.supportedGenerationMethods.includes("generateContent")
          )
          .map((m: any) => (m.name.startsWith("models/") ? m.name.replace("models/", "") : m.name));
      }
    } else {
      const errJson = await listRes.json().catch(() => ({}));
      if (errJson.error?.message) {
        lastError = new Error(`Google API Error: ${errJson.error.message}`);
      }
    }
  } catch (e: any) {
    console.warn("Failed to fetch dynamic models list:", e.message);
  }

  // Preferred models in priority order based on active Google AI models
  const priorityList = [
    "gemini-3.6-flash",
    "gemini-3.1-pro-preview",
    "gemini-3-flash",
    "gemini-2.0-flash",
    "gemini-2.0-flash-exp",
    "gemini-1.5-flash",
    "gemini-1.5-pro",
  ];

  // Filter availableModels to only include text generative models (exclude tts, audio, image-only)
  const validDiscovered = availableModels.filter(
    (name) =>
      !name.includes("-tts") &&
      !name.includes("-audio") &&
      !name.includes("embedding") &&
      !name.includes("a4b")
  );

  // Combine discovered models with priority list
  const modelsToTry: string[] = [];
  for (const p of priorityList) {
    modelsToTry.push(p);
  }
  for (const a of validDiscovered) {
    if (!modelsToTry.includes(a)) {
      modelsToTry.push(a);
    }
  }

  for (const model of modelsToTry) {
    try {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(trimmedKey)}`;

      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-goog-api-key": trimmedKey,
        },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.4,
            responseMimeType: "application/json",
          },
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        const errMsg =
          errorData.error?.message || `Gemini API responded with status ${response.status}`;
        throw new Error(errMsg);
      }

      const data = await response.json();
      const rawResponseText =
        data.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!rawResponseText) {
        throw new Error("No response generated from AI model");
      }

      // Parse JSON from model output
      const jsonMatch =
        rawResponseText.match(/```json\s*([\s\S]*?)\s*```/) ||
        rawResponseText.match(/\{[\s\S]*\}/);

      const parsed: AIProcessedNewsResult = JSON.parse(
        jsonMatch ? jsonMatch[1] || jsonMatch[0] : rawResponseText
      );

      // Validate & clean slug
      if (!parsed.suggestedSlug || parsed.suggestedSlug.length < 3) {
        parsed.suggestedSlug = transliterateSlug(parsed.title);
      } else {
        parsed.suggestedSlug = transliterateSlug(parsed.suggestedSlug);
      }

      return parsed;
    } catch (err: any) {
      lastError = err;
      console.warn(`Failed with model ${model}:`, err.message);
      // Try next model
    }
  }

  throw new Error(`AI Processing error: ${lastError?.message || "Failed to process news"}`);
}

/**
 * Smart Fallback when no Gemini API key is configured
 */
function generateFallbackNewsResult(
  rawText: string,
  sourceTitle?: string
): AIProcessedNewsResult {
  const cleaned = cleanRawText(rawText);
  const title = sourceTitle?.trim() || cleaned.slice(0, 70);
  const slug = transliterateSlug(title);

  const paragraphs = cleaned
    .split(/(?:\r?\n)+/)
    .map((p) => p.trim())
    .filter((p) => p.length > 20);

  const htmlContent =
    paragraphs.length > 0
      ? paragraphs.map((p) => `<p>${p}</p>`).join("\n")
      : `<p>${cleaned}</p>`;

  const sentences = cleaned.split(/[.।]/).map((s) => s.trim()).filter((s) => s.length > 10);
  const highlights = sentences.slice(0, 3).map((s) => `${s}।`);

  return {
    title: title,
    attractiveHeadlines: [
      title,
      `विशेष: ${title}`,
      `अपडेट: ${title} सम्बन्धी नयाँ विवरण`,
      `${title} बारे के भन्छन् जानकारहरू?`,
    ],
    content: htmlContent,
    highlights: highlights.length > 0 ? highlights : ["समाचारको मुख्य विवरण थपिएकाे छ।"],
    excerpt: sentences[0] ? `${sentences[0]}।` : title,
    metaTitle: `${title.slice(0, 55)} | Express Nepal`,
    metaDescription: cleaned.slice(0, 150),
    suggestedSlug: slug,
    suggestedCategory: "सूचना प्रविधि",
    isBreaking: false,
    breakingScore: 30,
    breakingReason: "API कुञ्जी विनाको सामान्य नमूना विश्लेषण। थप सटीक विश्लेषणका लागि Gemini API Key राख्नुहोस्।",
    imageSuggestions: {
      searchKeywords: ["Technology", "News", "Nepal"],
      description: "समाचारको मुख्य विषयसँग मिल्दोजुल्दो तस्बिर चयन गर्नुहोस्।",
    },
  };
}
